
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
env:
  CONTAINER_TAG: maya-hod/build_document:test
  SOURCE_PATH: /opt/source
  BUILD_PATH: /opt/source/build
  MAIN_PATH: /opt/source/main
  DOCUMENT_NAME: "Maya Hieroglyphs - The History of Decipherment"

jobs:
  compile_document:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build docker container
        uses: docker/build-push-action@v2
        with:
          context: .devcontainer
          load: true
          tags: ${{ env.CONTAINER_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Check tex files
        run: >-
          docker run --rm 
          -v $GITHUB_WORKSPACE:${{ env.SOURCE_PATH }}
          ${{ env.CONTAINER_TAG }} 
          bash -c ${{ env.SOURCE_PATH }}/chktexall.sh ${{ env.SOURCE_PATH }}

      - name: Compile document
        run: >-
          docker run --rm 
          -v $GITHUB_WORKSPACE:${{ env.SOURCE_PATH }}
          ${{ env.CONTAINER_TAG }}
          bash -c ${{ env.SOURCE_PATH }}/compile.sh 
            --source-path "${{ env.SOURCE_PATH }}" 
            --build-path "${{ env.BUILD_PATH}}" 
            --document-name ${{ env.DOCUMENT_NAME }}
            "${{ env.MAIN_PATH }}"

