
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
env:
  CONTAINER_TAG: maya-hod/build_document:test
  DOCUMENT_NAME: "Maya Hieroglyphs - The History of Decipherment"

jobs:
  compile_document:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build docker container
        uses: docker/build-push-action@v2
        with:
          context: .devcontainer
          load: true
          tags: ${{ env.CONTAINER_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Check tex files
        run: ./chktexall.sh
        shell: bash

      - name: Compile document
        run: docker run --rm -e "document_name=$DOCUMENT_NAME" -e "tex_file=/opt/sources/main" -e "build_path=opt/sources/build" -v $GITHUB_WORKSPACE:/opt/sources ${{ env.CONTAINER_TAG }}

