
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
env:
  CONTAINER_TAG: maya-hod/build_document:test

jobs:
  build_document:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build docker container
        uses: docker/build-push-action@v2
        with:
          context: .devcontainer
          load: true
          tags: ${{ env.CONTAINER_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build document
        run: docker run --rm -e "tex_file=/opt/sources/maya-hod" -e "build_path=opt/sources/build" -v $GITHUB_WORKSPACE:/opt/sources ${{ env.CONTAINER_TAG }}

